apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "erica.sundberg.90@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-account-key 
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - kind: Gateway
            name: shared-gateway
            namespace: shared-gateway